name: doc-fun
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - notebook
  - ipykernel
  - pyyaml
  - python-dotenv
  - beautifulsoup4
  - pandas
  - tabulate
  - pytest
  - pytest-mock
  - pygments
  - pip:
    - openai>=1.0.0